

insert into form_learn values(1, 1);
insert into form_learn values(2, 1);
insert into form_learn values(3, 1);
insert into form_learn values(4, 1);
insert into form_learn values(5, 1);
insert into form_learn values(6, 1);
insert into form_learn values(7, 1);
insert into form_learn values(8, 1);
insert into form_learn values(9, 1);
insert into form_learn values(10, 1);
insert into form_learn values(11, 1);
insert into form_learn values(12, 1);
insert into form_learn values(13, 1);
insert into form_learn values(14, 1);
insert into form_learn values(15, 1);
insert into form_learn values(16, 1);
insert into form_learn values(17, 1);
insert into form_learn values(18, 1);
insert into form_learn values(19, 1);
insert into form_learn values(20, 1);
insert into form_learn values(21, 1);
insert into form_learn values(22, 1);
insert into form_learn values(23, 1);
insert into form_learn values(24, 1);
insert into form_learn values(25, 1);
insert into form_learn values(26, 1);
insert into form_learn values(27, 1);
insert into form_learn values(28, 1);
insert into form_learn values(29, 1);
insert into form_learn values(30, 1);
insert into form_learn values(31, 1);
insert into form_learn values(32, 1);
insert into form_learn values(33, 1);
insert into form_learn values(34, 1);
insert into form_learn values(35, 1);
insert into form_learn values(36, 1);
insert into form_learn values(37, 1);
insert into form_learn values(38, 1);
insert into form_learn values(39, 1);
insert into form_learn values(40, 1);
insert into form_learn values(41, 1);
insert into form_learn values(42, 1);
insert into form_learn values(43, 1);
insert into form_learn values(44, 1);
insert into form_learn values(45, 1);
insert into form_learn values(46, 1);
insert into form_learn values(47, 1);
insert into form_learn values(48, 1);
insert into form_learn values(49, 1);
insert into form_learn values(50, 1);
insert into form_learn values(51, 2);
insert into form_learn values(52, 2);
insert into form_learn values(53, 2);
insert into form_learn values(54, 2);
insert into form_learn values(55, 2);
insert into form_learn values(56, 3);
insert into form_learn values(57, 3);
insert into form_learn values(58, 3);
insert into form_learn values(59, 3);
insert into form_learn values(60, 3);
insert into form_learn values(61, 3);
insert into form_learn values(62, 3);
insert into form_learn values(63, 3);
insert into form_learn values(64, 3);
insert into form_learn values(65, 3);
insert into form_learn values(66, 3);
insert into form_learn values(67, 3);
insert into form_learn values(68, 3);
insert into form_learn values(69, 3);
insert into form_learn values(70, 3);
insert into form_learn values(71, 3);
insert into form_learn values(72, 3);
insert into form_learn values(73, 3);
insert into form_learn values(74,3);
insert into form_learn values(75,3);
insert into form_learn values(76,3);
insert into form_learn values(77,3);
insert into form_learn values(78,3);
insert into form_learn values(79,3);
insert into form_learn values(80,3);
insert into form_learn values(81,3);
insert into form_learn values(82,3);
insert into form_learn values(83,3);
insert into form_learn values(84,3);
insert into form_learn values(85,3);
insert into form_learn values(86,3);
insert into form_learn values(87,3);
insert into form_learn values(88,3);
insert into form_learn values(89,3);
insert into form_learn values(90,3);
insert into form_learn values(91,3);
insert into form_learn values(92,3);
insert into form_learn values(93,3);
insert into form_learn values(94,3);
insert into form_learn values(95,3);
insert into form_learn values(96,3);
insert into form_learn values(97,3);
insert into form_learn values(98,3);
insert into form_learn values(99,3);
insert into form_learn values(100,3);
insert into form_learn values(101,3);
insert into form_learn values(102,3);
insert into form_learn values(103,3);
insert into form_learn values(104,3);
insert into form_learn values(105,3);
insert into form_learn values(106,3);
insert into form_learn values(107,3);
insert into form_learn values(108,3);
insert into form_learn values(109,3);
insert into form_learn values(110,3);
insert into form_learn values(111,3);
insert into form_learn values(112,3);
insert into form_learn values(113,3);
insert into form_learn values(114,3);
insert into form_learn values(115,3);
insert into form_learn values(116,3);
insert into form_learn values(117,3);